### ISSUE TITLE
Add rectmagnet element

### ISSUE THREAD

**Issue by ColwynGulliford** [ColwynGulliford/lume-gpt#8]
Users would like an element for handling the GPT rectmanget element.

**Comment by petr-lanl** [comment]
Can this element be independent of the beam parameters? I would like a simple description of xstart, zstart, xend, zend, B0, gap. It could be also specified by its center, Lx, Lz and two xhat, yhat vectors for rotations but I personally do not need that.

**Comment by ColwynGulliford** [comment]
I'll need to take a look at the GPT manual for that element, but I agree it's best to make it independent of the beam parameters if possible.

**Comment by ColwynGulliford** [comment]
I looked into this and here are a few things:

1. Using a rectmagnet with the Lattice designer will take a little extra work - the Lattice tools are really for making s-based lattice designs, where as GPT's rectmagnet object is more of a general 3d object.  It can be made to work, but requires more work than I thought.

2. In as s-based code you need a reference trajectory, and in order to make a reference particle follow that trajectory you need a reference momentum.  One can of course simply set the field but even for the sectormagnet examples, the momentum there should be thought of as the reference momentum - which is often something that is known more easily than say, the B-field value.

**Comment by petr-lanl** [comment]
Thank you for looking into this. I appreciate that.

From: Colwyn Gulliford ***@***.***>
Reply-To: ColwynGulliford/lume-gpt ***@***.***>
Date: Friday, September 29, 2023 at 4:47 AM
To: ColwynGulliford/lume-gpt ***@***.***>
Cc: "Anisimov, Petr Mikhaylovich" ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [ColwynGulliford/lume-gpt] Add rectmagnet element (Issue #8)


I looked into this and here are a few things:

  1.  Using a rectmagnet with the Lattice designer will take a little extra work - the Lattice tools are really for making s-based lattice designs, where as GPT's rectmagnet object is more of a general 3d object. It can be made to work, but requires more work than I thought.
  2.  In as s-based code you need a reference trajectory, and in order to make a reference particle follow that trajectory you need a reference momentum. One can of course simply set the field but even for the sectormagnet examples, the momentum there should be thought of as the reference momentum - which is often something that is known more easily than say, the B-field value.

**Comment by ColwynGulliford** [comment]
Added rectmagnet to latest release.
